/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { AUTH_TYPE } from 'aws-appsync';
const awsmobile = {
    "aws_project_region": "*******",
    "aws_cognito_region": "*******",
    "aws_user_pools_id": "*********",
    "aws_user_pools_web_client_id": "***************",
    "oauth": {},
    "aws_appsync_authenticationType" : AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    "aws_appsync_graphqlEndpoint": "https://************************.appsync-api.ap-south-1.amazonaws.com/graphql",
};

export default awsmobile;
